#!/usr/bin/env bash
#
# SDL2_build
# Martin Hrubý (hrubymar10), 2018
#

SDL2_VERSION="2.0.9"
SDL2_image_VERSION="2.0.4"
SDL2_mixer_VERSION="2.0.4"
SDL2_ttf_VERSION="2.0.14"

time_interval_to_string() {
        local START=$1
        local END=$2

        declare -i timestamp
        declare -i days
        declare -i hours
        declare -i minutes
        declare -i seconds
        timestamp=$END-$START

        days=$timestamp/60/60/24
        hours=$((($timestamp-($days*60*60*24))/60/60))
        minutes=$((($timestamp-($days*60*60*24)-($hours*60*60))/60))
        seconds=$((($timestamp-($days*60*60*24)-($hours*60*60)-($minutes*60))))
        if [ $days -eq 0 ]; then
        if [ $hours -eq 0 ]; then
                if [ $minutes -eq 0 ]; then
                echo "==> Operation took $seconds seconds ..."
                else
                echo "==> Operation took $minutes minutes and $seconds seconds ..."
                fi
        else
                echo "==> Operation took $hours hours $minutes minutes and $seconds seconds ..."
        fi
        else
        echo "==> Operation took $days days $hours hours $minutes minutes and $seconds seconds ..."
        fi
}

starttimestamp=$(date +%s)

MY_PATH=$(cd `dirname $0` && pwd)
if [ -z "$MY_PATH" ] ; then
        # error; for some reason, the path is not accessible
        # to the script (e.g. permissions re-evaled after suid)
        echo 'Error: Script path is for some reason not accessible' >&2
        exit 1  # fail
fi
cd "$MY_PATH"/../Sources

if ! [ -x "$(command -v wget)" ]; then
        echo 'Error: wget is not installed. Use for example Homebrew and install it. See https://brew.sh/' >&2
        exit 1
fi

if xcode-select --install 2>&1 | grep installed; then
        echo "==> Xcode Command Line Tools are installed..."
else
        echo "==> Xcode Command Line Tools aren't installed, installing..."
        xcode-select --install
fi

rm -rf SDL2
mkdir SDL2
cd SDL2

wget "https://www.libsdl.org/release/SDL2-$SDL2_VERSION.zip"
unzip "SDL2-$SDL2_VERSION.zip"
rm "SDL2-$SDL2_VERSION.zip"
ln -s "SDL2-$SDL2_VERSION" SDL
cd SDL/Xcode-iOS/SDL/
xcodebuild -project SDL.xcodeproj -target libSDL-iOS -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO BUILD_DIR="out"
xcodebuild -project SDL.xcodeproj -target libSDL-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BUILD_DIR="out"
lipo -create out/Release-iphonesimulator/libSDL2.a out/Release-iphoneos/libSDL2.a -o libSDL2.a
cd "$MY_PATH"/../Sources/SDL2
rm -rf ../../../Headers/SDL2/SDL2
mkdir -p ../../../Headers/SDL2/SDL2
cp -rf SDL/include/ ../../../Headers/SDL2/SDL2
rm -rf ../../../lib/libSDL2.a
cp -rf SDL/Xcode-iOS/SDL/libSDL2.a ../../../lib/libSDL2.a

wget "https://www.libsdl.org/projects/SDL_image/release/SDL2_image-$SDL2_image_VERSION.zip"
unzip "SDL2_image-$SDL2_image_VERSION.zip"
rm "SDL2_image-$SDL2_image_VERSION.zip"
cd "SDL2_image-$SDL2_image_VERSION/Xcode-iOS"
xcodebuild -project SDL_image.xcodeproj -target libSDL_image-iOS -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO BUILD_DIR="out"
xcodebuild -project SDL_image.xcodeproj -target libSDL_image-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BUILD_DIR="out"
lipo -create out/Release-iphonesimulator/libSDL2_image.a out/Release-iphoneos/libSDL2_image.a -o libSDL2_image.a
cd "$MY_PATH"/../Sources/SDL2
rm -rf ../../../Headers/SDL2/SDL_image.h
cp -rf "SDL2_image-$SDL2_image_VERSION/SDL_image.h" ../../../Headers/SDL2/SDL_image.h
rm -rf ../../../lib/libSDL2_image.a
cp -rf "SDL2_image-$SDL2_image_VERSION/Xcode-iOS/libSDL2_image.a" ../../../lib/libSDL2_image.a

wget "https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-$SDL2_mixer_VERSION.zip"
unzip "SDL2_mixer-$SDL2_mixer_VERSION.zip"
rm "SDL2_mixer-$SDL2_mixer_VERSION.zip"
cd "SDL2_mixer-$SDL2_mixer_VERSION/Xcode-iOS"
xcodebuild -project SDL_mixer.xcodeproj -target libSDL_mixer-iOS -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO BUILD_DIR="out"
xcodebuild -project SDL_mixer.xcodeproj -target libSDL_mixer-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BUILD_DIR="out"
lipo -create out/Release-iphonesimulator/libSDL2_mixer.a out/Release-iphoneos/libSDL2_mixer.a -o libSDL2_mixer.a
cd "$MY_PATH"/../Sources/SDL2
rm -rf ../../../Headers/SDL2/SDL_mixer.h
cp -rf "SDL2_mixer-$SDL2_mixer_VERSION/SDL_mixer.h" ../../../Headers/SDL2/SDL_mixer.h
rm -rf ../../../lib/libSDL2_mixer.a
cp -rf "SDL2_mixer-$SDL2_mixer_VERSION/Xcode-iOS/libSDL2_mixer.a" ../../../lib/libSDL2_mixer.a

wget "https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-$SDL2_ttf_VERSION.zip"
unzip "SDL2_ttf-$SDL2_ttf_VERSION.zip"
rm "SDL2_ttf-$SDL2_ttf_VERSION.zip"
cd "SDL2_ttf-$SDL2_ttf_VERSION/Xcode-iOS"
xcodebuild -project SDL_ttf.xcodeproj -target "Static Library" -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO BUILD_DIR="out"
xcodebuild -project SDL_ttf.xcodeproj -target "Static Library" -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BUILD_DIR="out"
lipo -create out/Release-iphonesimulator/libSDL2_ttf.a out/Release-iphoneos/libSDL2_ttf.a -o libSDL2_ttf.a
cd "$MY_PATH"/../Sources/SDL2
rm -rf ../../../Headers/SDL2/SDL_ttf.h
cp -rf "SDL2_ttf-$SDL2_ttf_VERSION/SDL_ttf.h" ../../../Headers/SDL2/SDL_ttf.h
rm -rf ../../../lib/libSDL2_ttf.a
cp -rf "SDL2_ttf-$SDL2_ttf_VERSION/Xcode-iOS/libSDL2_ttf.a" ../../../lib/libSDL2_ttf.a

echo "==> DONE ..."
echo
time_interval_to_string "$starttimestamp" "$(date +%s)"
echo